version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=secure_passwoard
    ports:
      - '5432:5432'
